"""
Prompt templates for AI operations

Centralized prompt management with consistent formatting and validation.
"""

from .email_prompts import (
    EMAIL_ANALYSIS_SYSTEM,
    EMAIL_ANALYSIS_PROMPT,
    EMAIL_COMPOSE_SYSTEM,
    EMAIL_REPLY_PROMPT,
    EMAIL_NEW_PROMPT,
    EMAIL_FOLLOWUP_PROMPT,
    EMAIL_THANKYOU_PROMPT,
    EMAIL_GENERIC_PROMPT,
    AUTO_REPLY_PROMPT,
    AUTO_ACKNOWLEDGMENT_PROMPT,
    EMAIL_CONVERSATIONAL_LIST,
    EMAIL_CONVERSATIONAL_EMPTY
)

from .document_prompts import (
    DOCUMENT_SUMMARY_SYSTEM,
    DOCUMENT_SUMMARY_PROMPT,
    DOCUMENT_KEY_POINTS,
    MEETING_PREP_SYSTEM,
    MEETING_PREP_PROMPT,
    MEETING_SUMMARY_SYSTEM,
    MEETING_SUMMARY_PROMPT
)

from .agent_prompts import (
    get_agent_system_prompt,
    INTENT_CLASSIFICATION_PROMPT,
    ENTITY_EXTRACTION_PROMPT,
    CLARIFICATION_PROMPT,
    MULTI_INTENT_PROMPT
)

from .orchestrator_prompts import (
    get_orchestrator_master_prompt
)

from .conversational_prompts import (
    get_orchestrator_conversational_prompt,
    get_conversational_enhancement_prompt
)

from .tool_prompts import (
    TASK_CREATE_SYSTEM,
    TASK_CREATE_PROMPT,
    TASK_DESCRIPTION_EXTRACTION,
    TASK_DUE_DATE_EXTRACTION,
    TASK_PRIORITY_EXTRACTION,
    TASK_CATEGORY_DETECTION,
    TASK_CREATE_SUCCESS,
    CALENDAR_CREATE_SYSTEM,
    CALENDAR_CREATE_PROMPT,
    EMAIL_SEARCH_SYSTEM,
    EMAIL_SEARCH_PROMPT,
    TOOL_SELECTION_PROMPT,
    TOOL_RESULT_SUMMARY,
    TASK_SEARCH_RESPONSE,
    TASK_COMPLETE_RESPONSE,
    TASK_DELETE_RESPONSE,
    TASK_LIST_RESPONSE,
    TASK_ANALYTICS_RESPONSE
)

from .task_prompts import (
    TASK_CONVERSATIONAL_LIST,
    TASK_CONVERSATIONAL_EMPTY
)

from .error_prompts import (
    ERROR_MESSAGE_PROMPT,
    NO_RESULTS_PROMPT,
    VALIDATION_PROMPT,
    MULTI_STEP_DETECTION_PROMPT,
    QUERY_DECOMPOSITION_PROMPT,
    CALENDAR_UNAVAILABLE_PROMPT,
    CALENDAR_TASK_MISROUTE_PROMPT
)

from .calendar_prompts import (
    CALENDAR_CREATE_SUCCESS,
    CALENDAR_UPDATE_SUCCESS,
    CALENDAR_DELETE_SUCCESS,
    CALENDAR_LIST_EVENTS,
    CALENDAR_NO_EVENTS,
    CALENDAR_SEARCH_RESULTS,
    CALENDAR_NO_SEARCH_RESULTS,
    CALENDAR_CONFLICT_DETECTED,
    CALENDAR_EVENT_NOT_FOUND,
    CALENDAR_ACTION_ERROR,
    CALENDAR_CONVERSATIONAL_LIST,
    CALENDAR_CONVERSATIONAL_EMPTY
)

from .blog_prompts import (
    BLOG_COMPLETION_SYSTEM,
    BLOG_COMPLETION_PROMPT
)

from .conversational_prompts import (
    EMAIL_NO_RESULTS_GENERAL_PROMPT,
    EMAIL_PRIORITY_NO_RESULTS_PROMPT,
    EMAIL_PRIORITY_FOUND_SINGLE,
    EMAIL_PRIORITY_FOUND_MULTIPLE,
    EMAIL_GENERAL_RESPONSE_PROMPT,
    EMAIL_SUMMARY_SINGLE,
    EMAIL_SUMMARY_MULTIPLE
)

from .financial_prompts import (
    SPENDING_ANALYSIS_SYSTEM,
    SPENDING_ANALYSIS_PROMPT,
    VENDOR_ANALYSIS_SYSTEM,
    VENDOR_ANALYSIS_PROMPT
)

from .notion_prompts import (
    NOTION_CLASSIFICATION_SYSTEM,
    NOTION_CLASSIFICATION_PROMPT,
    NOTION_CREATE_PAGE_SYSTEM,
    NOTION_CREATE_PAGE_PROMPT,
    NOTION_CREATE_SUCCESS,
    NOTION_SEARCH_SYSTEM,
    NOTION_SEARCH_PROMPT,
    NOTION_SEARCH_RESULTS,
    NOTION_NO_SEARCH_RESULTS,
    NOTION_UPDATE_SUCCESS,
    NOTION_CONVERSATIONAL_LIST,
    NOTION_CONVERSATIONAL_EMPTY,
    NOTION_TITLE_GENERATION_PROMPT,
    NOTION_ENTITY_EXTRACTION_PROMPT
)

from .context_prompts import (
    CONTEXT_EXTRACTION_PROMPT
)

from .decomposition_prompts import (
    QUERY_DECOMPOSITION_PROMPT
)

# Utilities are internal - import directly: from .utils import format_prompt

__all__ = [
    # Email prompts
    "EMAIL_ANALYSIS_SYSTEM",
    "EMAIL_ANALYSIS_PROMPT",
    "EMAIL_COMPOSE_SYSTEM",
    "EMAIL_REPLY_PROMPT",
    "EMAIL_NEW_PROMPT",
    "EMAIL_FOLLOWUP_PROMPT",
    "EMAIL_THANKYOU_PROMPT",
    "EMAIL_GENERIC_PROMPT",
    "AUTO_REPLY_PROMPT",
    "AUTO_ACKNOWLEDGMENT_PROMPT",
    "EMAIL_CONVERSATIONAL_LIST",
    "EMAIL_CONVERSATIONAL_EMPTY",
    
    # Document prompts
    "DOCUMENT_SUMMARY_SYSTEM",
    "DOCUMENT_SUMMARY_PROMPT",
    "DOCUMENT_KEY_POINTS",
    "MEETING_PREP_SYSTEM",
    "MEETING_PREP_PROMPT",
    "MEETING_SUMMARY_SYSTEM",
    "MEETING_SUMMARY_PROMPT",
    
    # Agent prompts
    "get_agent_system_prompt",
    "INTENT_CLASSIFICATION_PROMPT",
    "ENTITY_EXTRACTION_PROMPT",
    "CLARIFICATION_PROMPT",
    "MULTI_INTENT_PROMPT",
    
    # Orchestrator prompts
    "get_orchestrator_master_prompt",
    "get_orchestrator_conversational_prompt",
    "get_conversational_enhancement_prompt",
    
    # Tool prompts
    "TASK_CREATE_SYSTEM",
    "TASK_CREATE_PROMPT",
    "TASK_DESCRIPTION_EXTRACTION",
    "TASK_DUE_DATE_EXTRACTION",
    "TASK_PRIORITY_EXTRACTION",
    "TASK_CATEGORY_DETECTION",
    "TASK_CREATE_SUCCESS",
    "CALENDAR_CREATE_SYSTEM",
    "CALENDAR_CREATE_PROMPT",
    "EMAIL_SEARCH_SYSTEM",
    "EMAIL_SEARCH_PROMPT",
    "TOOL_SELECTION_PROMPT",
    "TOOL_RESULT_SUMMARY",
    "TASK_SEARCH_RESPONSE",
    "TASK_COMPLETE_RESPONSE",
    "TASK_DELETE_RESPONSE",
    "TASK_LIST_RESPONSE",
    "TASK_ANALYTICS_RESPONSE",
    
    # Error handling prompts
    "ERROR_MESSAGE_PROMPT",
    "NO_RESULTS_PROMPT",
    "VALIDATION_PROMPT",
    "MULTI_STEP_DETECTION_PROMPT",
    "QUERY_DECOMPOSITION_PROMPT",
    "CALENDAR_UNAVAILABLE_PROMPT",
    "CALENDAR_TASK_MISROUTE_PROMPT",
    
    # Calendar event prompts
    "CALENDAR_CREATE_SUCCESS",
    "CALENDAR_UPDATE_SUCCESS",
    "CALENDAR_DELETE_SUCCESS",
    "CALENDAR_LIST_EVENTS",
    "CALENDAR_NO_EVENTS",
    "CALENDAR_SEARCH_RESULTS",
    "CALENDAR_NO_SEARCH_RESULTS",
    "CALENDAR_CONFLICT_DETECTED",
    "CALENDAR_EVENT_NOT_FOUND",
    "CALENDAR_ACTION_ERROR",
    "CALENDAR_CONVERSATIONAL_LIST",
    "CALENDAR_CONVERSATIONAL_EMPTY",
    
    # Blog prompts
    "BLOG_COMPLETION_SYSTEM",
    "BLOG_COMPLETION_PROMPT",
    
    # Conversational response prompts
    "EMAIL_NO_RESULTS_GENERAL_PROMPT",
    "EMAIL_PRIORITY_NO_RESULTS_PROMPT",
    "EMAIL_PRIORITY_FOUND_SINGLE",
    "EMAIL_PRIORITY_FOUND_MULTIPLE",
    "EMAIL_GENERAL_RESPONSE_PROMPT",
    "EMAIL_SUMMARY_SINGLE",
    "EMAIL_SUMMARY_MULTIPLE",
    
    # Financial analysis prompts
    "SPENDING_ANALYSIS_SYSTEM",
    "SPENDING_ANALYSIS_PROMPT",
    "VENDOR_ANALYSIS_SYSTEM",
    "VENDOR_ANALYSIS_PROMPT",
    
    # Notion prompts
    "NOTION_CLASSIFICATION_SYSTEM",
    "NOTION_CLASSIFICATION_PROMPT",
    "NOTION_CREATE_PAGE_SYSTEM",
    "NOTION_CREATE_PAGE_PROMPT",
    "NOTION_CREATE_SUCCESS",
    "NOTION_SEARCH_SYSTEM",
    "NOTION_SEARCH_PROMPT",
    "NOTION_SEARCH_RESULTS",
    "NOTION_NO_SEARCH_RESULTS",
    "NOTION_UPDATE_SUCCESS",
    "NOTION_CONVERSATIONAL_LIST",
    "NOTION_CONVERSATIONAL_EMPTY",
    "NOTION_TITLE_GENERATION_PROMPT",
    "NOTION_ENTITY_EXTRACTION_PROMPT",
    
    # Task operation prompts (added to TOOL_PROMPTS section above)
    "TASK_SEARCH_RESPONSE",
    "TASK_COMPLETE_RESPONSE",
    "TASK_DELETE_RESPONSE",
    "TASK_LIST_RESPONSE",
    "TASK_ANALYTICS_RESPONSE",
    
    # Task conversational prompts
    "TASK_CONVERSATIONAL_LIST",
    "TASK_CONVERSATIONAL_EMPTY",
    
    # Context extraction prompts
    "CONTEXT_EXTRACTION_PROMPT",
    
    # Query decomposition prompts
    "QUERY_DECOMPOSITION_PROMPT",
]

