"""add last_active_at to sessions

Revision ID: dc2494b491ca
Revises: add_oauth_states_table
Create Date: 2025-12-11 23:32:38.351135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc2494b491ca'
down_revision: Union[str, None] = 'add_oauth_states_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_memory')
    op.drop_index(op.f('idx_user_behavior_user_id'), table_name='user_behavior_profiles')
    op.drop_table('user_behavior_profiles')
    op.drop_table('query_patterns')
    op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_table('langchain_pg_embedding')
    op.drop_index(op.f('idx_apikey_hash_active'), table_name='api_keys')
    op.drop_index(op.f('idx_apikey_user_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('langchain_pg_collection')
    op.drop_index(op.f('idx_user_cap_prefs_user_id'), table_name='user_capability_preferences')
    op.drop_table('user_capability_preferences')
    op.drop_index(op.f('idx_pattern_clusters_confidence'), table_name='pattern_clusters')
    op.drop_table('pattern_clusters')
    op.drop_index(op.f('idx_baseline_pattern_sig'), table_name='baseline_metrics')
    op.drop_table('baseline_metrics')
    op.drop_index(op.f('idx_exec_patterns_last_seen'), table_name='execution_patterns')
    op.drop_index(op.f('idx_exec_patterns_signature'), table_name='execution_patterns')
    op.drop_index(op.f('idx_exec_patterns_user'), table_name='execution_patterns')
    op.drop_table('execution_patterns')
    op.drop_index(op.f('idx_anomalies_type_severity'), table_name='detected_anomalies')
    op.drop_index(op.f('idx_anomalies_unresolved'), table_name='detected_anomalies')
    op.drop_index(op.f('idx_anomalies_user'), table_name='detected_anomalies')
    op.drop_table('detected_anomalies')
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of event: login_success, login_failure, logout, token_refresh_success, etc.',
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Additional event-specific data in JSON format',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='Client IP address (IPv4 or IPv6)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the event was successful',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Audit log for security and authentication events',
        schema=None
    )
    op.alter_column('conversation_messages', 'agent_plan',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'execution_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('oauth_states_state_key'), 'oauth_states', type_='unique')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.drop_table_comment(
        'oauth_states',
        existing_comment='Stores OAuth CSRF states for database-backed session security',
        schema=None
    )
    op.add_column('sessions', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_sessions_created_at'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_expires_at'), table_name='sessions')
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_last_active_at'), 'sessions', ['last_active_at'], unique=False)
    op.drop_index(op.f('idx_user_settings_created_at'), table_name='user_settings')
    op.alter_column('users', 'initial_indexing_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'total_emails_indexed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'indexing_progress_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email_indexed'), table_name='users')
    op.drop_index(op.f('idx_users_indexing_status'), table_name='users')
    op.drop_index(op.f('idx_users_initial_complete'), table_name='users')
    op.drop_index(op.f('idx_users_is_admin'), table_name='users')
    op.drop_index(op.f('idx_users_last_email_synced'), table_name='users', postgresql_where='(last_email_synced_at IS NOT NULL)')
    op.drop_index(op.f('idx_users_last_indexed'), table_name='users')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email_indexed'), 'users', ['email_indexed'], unique=False)
    op.create_index(op.f('ix_users_indexing_status'), 'users', ['indexing_status'], unique=False)
    op.create_index(op.f('ix_users_initial_indexing_complete'), 'users', ['initial_indexing_complete'], unique=False)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_last_email_synced_at'), 'users', ['last_email_synced_at'], unique=False)
    op.create_index(op.f('ix_users_last_indexed_timestamp'), 'users', ['last_indexed_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_indexed_timestamp'), table_name='users')
    op.drop_index(op.f('ix_users_last_email_synced_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_initial_indexing_complete'), table_name='users')
    op.drop_index(op.f('ix_users_indexing_status'), table_name='users')
    op.drop_index(op.f('ix_users_email_indexed'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_index(op.f('idx_users_last_indexed'), 'users', ['last_indexed_timestamp'], unique=False)
    op.create_index(op.f('idx_users_last_email_synced'), 'users', [sa.literal_column('last_email_synced_at DESC')], unique=False, postgresql_where='(last_email_synced_at IS NOT NULL)')
    op.create_index(op.f('idx_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('idx_users_initial_complete'), 'users', ['initial_indexing_complete'], unique=False)
    op.create_index(op.f('idx_users_indexing_status'), 'users', ['indexing_status'], unique=False)
    op.create_index(op.f('idx_users_email_indexed'), 'users', ['email_indexed'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('users', 'indexing_progress_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('users', 'total_emails_indexed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'initial_indexing_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_user_settings_created_at'), 'user_settings', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_sessions_last_active_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.create_index(op.f('idx_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('idx_sessions_created_at'), 'sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('sessions', 'last_active_at')
    op.create_table_comment(
        'oauth_states',
        'Stores OAuth CSRF states for database-backed session security',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=False)
    op.create_unique_constraint(op.f('oauth_states_state_key'), 'oauth_states', ['state'], postgresql_nulls_not_distinct=False)
    op.alter_column('conversation_messages', 'execution_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'agent_plan',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table_comment(
        'audit_logs',
        'Audit log for security and authentication events',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('idx_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               comment='Whether the event was successful',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Client IP address (IPv4 or IPv6)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'event_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional event-specific data in JSON format',
               existing_nullable=True)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of event: login_success, login_failure, logout, token_refresh_success, etc.',
               existing_nullable=False)
    op.create_table('detected_anomalies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('affected_patterns', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('suggested_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acknowledged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('detected_anomalies_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('detected_anomalies_pkey'))
    )
    op.create_index(op.f('idx_anomalies_user'), 'detected_anomalies', ['user_id'], unique=False)
    op.create_index(op.f('idx_anomalies_unresolved'), 'detected_anomalies', ['resolved', 'detected_at'], unique=False)
    op.create_index(op.f('idx_anomalies_type_severity'), 'detected_anomalies', ['anomaly_type', 'severity'], unique=False)
    op.create_table('execution_patterns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signature', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('occurrence_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('avg_duration_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('execution_patterns_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('execution_patterns_pkey'))
    )
    op.create_index(op.f('idx_exec_patterns_user'), 'execution_patterns', ['user_id'], unique=False)
    op.create_index(op.f('idx_exec_patterns_signature'), 'execution_patterns', ['signature'], unique=False)
    op.create_index(op.f('idx_exec_patterns_last_seen'), 'execution_patterns', ['last_seen_at'], unique=False)
    op.create_table('baseline_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pattern_signature', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('avg_duration', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('min_duration', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('max_duration', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('baseline_metrics_pkey')),
    sa.UniqueConstraint('pattern_signature', name=op.f('baseline_metrics_pattern_signature_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_baseline_pattern_sig'), 'baseline_metrics', ['pattern_signature'], unique=False)
    op.create_table('pattern_clusters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pattern_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('centroid_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('characteristics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('member_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.7'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pattern_clusters_pkey')),
    sa.UniqueConstraint('cluster_id', name=op.f('pattern_clusters_cluster_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_pattern_clusters_confidence'), 'pattern_clusters', ['confidence'], unique=False)
    op.create_table('user_capability_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_format', sa.VARCHAR(length=50), server_default=sa.text("'conversational'::character varying"), autoincrement=False, nullable=True),
    sa.Column('preferred_detail_level', sa.VARCHAR(length=50), server_default=sa.text("'standard'::character varying"), autoincrement=False, nullable=True),
    sa.Column('include_timestamps', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('include_statistics', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('use_emojis', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('use_markdown', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('max_items_shown', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('group_by_domain', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('show_alternatives', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('include_actions', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_capability_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_capability_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_capability_preferences_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_cap_prefs_user_id'), 'user_capability_preferences', ['user_id'], unique=False)
    op.create_table('langchain_pg_collection',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
    sa.UniqueConstraint('name', name='langchain_pg_collection_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_keys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey'))
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('idx_apikey_user_active'), 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_apikey_hash_active'), 'api_keys', ['key_hash', 'is_active'], unique=False)
    op.create_table('langchain_pg_embedding',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.create_index(op.f('ix_cmetadata_gin'), 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_table('query_patterns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pattern', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('success_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failure_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('query_patterns_pkey'))
    )
    op.create_table('user_behavior_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pattern_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('total_patterns', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('avg_execution_time', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('preferred_domains', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('preferred_intents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_behavior_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_behavior_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_behavior_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_behavior_user_id'), 'user_behavior_profiles', ['user_id'], unique=False)
    op.create_table('execution_memory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tools_used', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('step_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('execution_memory_pkey'))
    )
    # ### end Alembic commands ###
